Move git configuration to .config

diff --git a/.config/git/githooks/pre-push b/.config/git/githooks/pre-push
--- a/.config/git/githooks/pre-push
+++ b/.config/git/githooks/pre-push
@@ -2,6 +2,9 @@
 set -o errexit -o nounset -o pipefail
 #set -x # For debugging
 
+BASENAME=$(basename "$0")
+DIRNAME="$(dirname "$(readlink -f "$0")")"
+
 # $1 -- Name of the remote to which the push is being done
 # $2 -- URL to which the push is being done
 
@@ -21,4 +24,18 @@ if git log --since="$SINCE" --format='%s' | grep -E '^fixup!' > /dev/null; then
 	git log --since="$SINCE" --format='%s' | grep -E '^fixup!'
 	echo
 	exit 1
+fi
+
+SCRIPT_FILE=".git/hooks/$BASENAME"
+if [ -e "$SCRIPT_FILE" ]; then
+	"$SCRIPT_FILE"
+else
+	exit 0
+fi
+
+if [ $? -ne 0 ]; then
+	echo "$BASENAME hook error"
+	exit 1
+else
+	exit 0
 fi
